/**
 * The four steps, alternating sides. Every frame holds a real capture from
 * `public/showcase`, regenerated by `npm run showcase:capture` against the
 * running product, rather than a drawing of the product. The mockup this
 * layout comes from used hand-built UI here, including a row advertising
 * Notion, Confluence and Slack connectors that do not exist; that row is
 * deliberately not carried over.
 */
const CHECK = (
  <span className="chk" aria-hidden="true">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
      <path d="M5 12l4 4L19 7" />
    </svg>
  </span>
);

interface Feature {
  eyebrow: string;
  title: string;
  body: string;
  points: string[];
  img: string;
  alt: string;
  label: string;
}

const FEATURES: Feature[] = [
  {
    eyebrow: "Grounded answers",
    title: "Knows your product.",
    body: "Point Nexo at the help centre and documentation you already maintain. It fetches, chunks and embeds them, then answers from that knowledge and cites the source every time.",
    points: [
      "Crawl a help-centre URL or upload a PDF",
      "Hybrid retrieval, semantic and keyword together",
      "Every answer links back to what it used",
      "Nothing invented: grounded, or it hands over",
    ],
    img: "/showcase/teach.png",
    alt: "The Nexo knowledge page listing ingested sources with their chunk counts and index times",
    label: "Knowledge",
  },
  {
    eyebrow: "Cited every time",
    title: "Answers you can check.",
    body: "Each reply carries the sources it was built from and the confidence behind it, so an operator can see why Nexo said what it said instead of taking it on trust.",
    points: [
      "The source behind every answer, named",
      "A confidence score on the reply itself",
      "Reads as a normal conversation to the customer",
    ],
    img: "/showcase/answer.png",
    alt: "A Nexo conversation answering a billing question with a cited source and a confidence score",
    label: "Conversation",
  },
  {
    eyebrow: "Escalation-first",
    title: "Always an exit.",
    body: "When confidence falls below the line, the conversation goes to a person with everything attached: what was asked, what Nexo found, and why it stopped.",
    points: [
      "A confidence gate on every reply",
      "A visible path to a human at any point",
      "The handoff carries the whole thread",
      "No dead ends, no loops, no shrug",
    ],
    img: "/showcase/escalate.png",
    alt: "The context Nexo attaches to a handoff: the reason, what the customer asked, and what knowledge matched",
    label: "Handoff",
  },
  {
    eyebrow: "One queue",
    title: "Your team sees everything.",
    body: "Every conversation Nexo could not finish lands in one place, with how long it has been waiting and whether anyone has picked it up.",
    points: [
      "Everything waiting on a person, in one queue",
      "An owner per conversation, so nothing is assumed",
      "The questions Nexo could not answer, grouped",
    ],
    img: "/showcase/operate.png",
    alt: "The Nexo overview listing conversations waiting on a person and how long each has waited",
    label: "Overview",
  },
];

export function Features() {
  return (
    <div className="wrap" id="platform">
      {FEATURES.map((feature, i) => (
        <section className={`feature reveal${i % 2 === 1 ? " flip" : ""}`} key={feature.title}>
          <div className="feature-text">
            <span className="l-eyebrow">{feature.eyebrow}</span>
            <h2>{feature.title}</h2>
            <p>{feature.body}</p>
            <ul className="feature-list">
              {feature.points.map((point) => (
                <li key={point}>
                  {CHECK}
                  {point}
                </li>
              ))}
            </ul>
          </div>
          <div className="mock">
            <div className="mock-bar">
              <i />
              <i />
              <i />
              <span className="mock-url">{feature.label}</span>
            </div>
            <div className="mock-shot">
              <img src={feature.img} alt={feature.alt} loading="lazy" />
            </div>
          </div>
        </section>
      ))}
    </div>
  );
}
